<div id="dlgLoginForm" style="display: none" title="Login">
  <p class="validateTips" style="color: red"></p><br>
  <form id="frmBeerLogin" method="post">
    <fieldset>
      <table width="100%" border="0">
        <tr><td>EMAIL:</td></tr>
        <tr><td><input type="text" id="email" name="beerlift[email]" style="width: 100%;"></td></tr>
        <tr><td>&nbsp;</td></tr>
        <tr><td>PASSWORD:</td></tr>
        <tr><td><input type="password" id="password" name="beerlift[password]" style="width: 100%;"></td></tr>        
      </table>

      <!-- Allow form submission with keyboard without duplicating the dialog button -->
      <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
    </fieldset>
  </form>
</div>