<div id="dlgThankYou" style="display: none" title="">
	<table width="100%"><tr><td align="center">
		<tr>
			<td>
				<table width="508" border="0" cellspacing="0" cellpadding="0">
					<tr>
						<td colspan="3" width="508"><img src="<?php echo $image_path.'beerlift/thankyou_01.png'; ?>" /></td>
					</tr>
					<tr>
						<td width="83" valign="top"><img src="<?php echo $image_path.'beerlift/thankyou_02.png'; ?>" /></td>
						<td width="381" valign="top" bgcolor="fdab03" align="center">
							<font face="Verdana, Arial, Helvetica, sans-serif" style="font-size:18px">We have received your video and will process it manually within 48hrs.</font><br />
						</td>
						<td width="44" valign="top"><img src="<?php echo $image_path.'beerlift/thankyou_03.png'; ?>" /></td>
					</tr>
					<tr>
						<td colspan="3" width="508" valign="top"><img src="<?php echo $image_path.'beerlift/thankyou_04.png'; ?>" /></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>