<?php
	$item = [];

	$todo = $psgData;

	$item['id']          = $todo ? $todo->getId() : "";
	$item['title']       = $todo ? $todo->getTitle() : "";
	$item['description'] = $todo ? $todo->getDescription() : "";
?>

<h1>Things to Do</h1>
<form id="todo-form" action=" <?php echo $this->helper('todo')->getTodoUrl('create'); ?>" method="post">
	<input id="todo[id]" name="todo[id]" value="<?php echo $item['id'];?>" type="hidden">
	<ul class="form-list">
		<li>
			<label class="required" for="title"><em>*</em>Title</label>
			<div class="input-box">
				<input id="title" class="input-text required-entry validate-title" title="Title" name="todo[title]" value="<?php echo $this->htmlEscape($item['title']) ?>" type="text">
			</div>
		</li>
		<li>
			<label class="required" for="description"><em>*</em>Description</label>
			<div class="input-box">
				<textarea id="pass" class="input-text required-entry validate-description" title="Description" name="todo[description]"><?php echo $this->htmlEscape($item['description']) ?></textarea>
			</div>
		</li>
	</ul>
    <button id="send2" class="button" title="Submit"><span><span>Submit</span></span></button>
    <a href="javascript: window.history.back()">Back</a>
	* Required Fields
</form>

<script type="text/javascript">
	//< ![CDATA[
		var customForm = new VarienForm('todo-form');
	//]]>
</script>
