
<p> <a href="<?php echo $this->helper('todo')->getTodoUrl('add'); ?>">Add</a> </p>
<table border="1">
	<tr>
		<td>ID</td>
		<td>Title</td>
		<td>Description</td>
		<td>Action</td>
	</tr>
	<?php foreach($todos as $todo): ?>
		<tr>
			<td><?php echo $todo->getId(); ?></td>
			<td><?php echo $todo->getTitle(); ?></td>
			<td><?php echo $todo->getDescription(); ?></td>
			<td>
				<a href="<?php echo $this->helper('todo')->getTodoUrl('edit', $todo->getId()); ?>">Edit</a> | 
				<a href="<?php echo $this->helper('todo')->getTodoUrl('delete', $todo->getId()); ?>" onclick="return confirm('Are you sure you want to delete?')">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>