
<?php $todo = $psgData; // Mage::getModel('todo/todo')->load($this->id); ?>

<h1>Things to Do</h1>
<form id="todo-form" action=" <?php echo $this->helper('todo')->getTodoUrl('update'); ?>" method="post">
	<input id="todo[id]" name="todo[id]" value="<?php echo $todo->getId();?>" type="hidden">
	<ul class="form-list">
		<li>
			<label class="required" for="title"><em>*</em>Title</label>
			<div class="input-box">
				<input id="title" class="input-text required-entry validate-title" title="Title" name="todo[title]" value="<?php echo $this->htmlEscape($todo->getTitle()) ?>" type="text">
			</div>
		</li>
		<li>
			<label class="required" for="description"><em>*</em>Description</label>
			<div class="input-box">
				<textarea id="pass" class="input-text required-entry validate-description" title="Description" name="todo[description]"><?php echo $this->htmlEscape($todo->getDescription()) ?></textarea>
			</div>
		</li>
	</ul>
    <button id="send2" class="button" title="Submit"><span><span>Submit</span></span></button>
    <a href="javascript: window.history.back()">Back</a>
	* Required Fields
</form>

<script type="text/javascript">
	//< ![CDATA[
		var customForm = new VarienForm('todo-form');
	//]]>
</script>